server {
  listen 80;

  # Directorio raíz donde están los archivos de tu app
  root /usr/share/nginx/html;
  # El archivo por defecto a servir
  index index.html;

  # La regla mágica
  location / {
    # Intenta servir el archivo que se pide ($uri)
    # Si es un directorio, intenta servirlo ($uri/)
    # Si ninguna de las anteriores funciona, sirve /index.html
    try_files $uri $uri/ /index.html;
  }
}